### ISSUE TITLE
Would be nice if there is preview demo ;)

### ISSUE THREAD

**Issue by Anthonyeef** [ahaasler/hexo-theme-colos#7]

**Comment by ahaasler** [comment]
There's a demo site in [hexo-theme-colos-demo](https://github.com/ahaasler/hexo-theme-colos-demo). You can also see a [live demo](http://colos.adrianhaasler.com/).

Keep in mind that the theme is currently in alpha stages, it has no style yet (looks plain and default). I'm working in migrating the multilingual features to plugins, see #4.
